import os
from util import scanFiles
env = Environment(ENV=os.environ)

cp_imgs  = env.Command('dummy1', [], './copy_images.sh')
form_tex = env.Command('dummy2', [], 'cat ../../header.tex electron_pid_standalone.tex > electron_pid.tex')
pdf      = env.PDF(target = 'electron_pid.pdf',  source = 'electron_pid.tex')

Depends(pdf, form_tex)
Depends(form_tex, cp_imgs)

cleans = scanFiles('.', accept=["electron_pid*", "*.aux"], reject=[".tex"])
Clean('electron_pid.html', cleans)
