import sys
import os

sys.path.insert(0, '../../../..')

from scanFiles import scan_files

env = Environment(ENV=os.environ)

cp_imgs  = env.Command('dummy1', [], './copy_images.sh')
form_tex = env.Command('dummy2', [], 'cat ../../header.tex proton_pid_standalone.tex > proton_pid.tex')
pdf      = env.PDF(target = 'proton_pid.pdf',  source = 'proton_pid.tex')

#Depends(pdf, form_tex) # this dependency is not working. The result of form_tex is kept in the repo to avoid this problem
Depends(form_tex, cp_imgs)

cleans = scan_files('.', accept=["proton_pid*", "*.aux"], reject=[".tex"])
Clean('proton_pid.html', cleans)
