#!/bin/zsh

# collecting bibliographies

base_dir=/opt/projects/pubs/pi0_resonance_regions
#ana_dirs=(   pi0_selection)
ana_dirs=(pid/electron pid/proton vertex)

rm -rf pi0.tex pi0_bib.tex img
cat header.tex pi0_content.tex > pi0.tex

echo "\\\begin{thebibliography}{mybib}" > pi0_bib.tex
for b in $ana_dirs
do
  echo " > processing bib and images in $b "
  grep bibitem "$base_dir"/"$b"/*bib*.tex >>  pi0_bib.tex
  ./$b/copy_images.sh
done
echo "\\\end{thebibliography}" >> pi0_bib.tex


scons -c
scons


