import os

env = Environment(ENV=os.environ)
env['ENV']['TEXINPUTS']='.:'
env['ENV']['TEXINPUTS']+='/opt/projects/analysis/pid/electron/docs//:'
env['ENV']['TEXINPUTS']+='/opt/projects/analysis/pid/proton/docs//:'
env['ENV']['TEXINPUTS']+='/opt/projects/analysis/vertex/docs//:'
env['ENV']['TEXINPUTS']+='/opt/projects/analysis/fiducial/electron/docs//:'
env['ENV']['TEXINPUTS']+='/opt/projects/analysis/pi0_selection/docs//:'


pdf    = env.PDF(target  = 'pi0.pdf',  source = 'pi0.tex')
