import sys
import os

sys.path.insert(0, '../../../..')

from scanFiles import scan_files

env = Environment(ENV=os.environ)

cp_imgs  = env.Command('dummy1', [], './copy_images.sh')
form_tex = env.Command('dummy2', [], 'cat ../../header.tex proton_fiducial_standalone.tex > proton_fiducial.tex')
pdf      = env.PDF(target = 'proton_fiducial.pdf',  source = 'proton_fiducial.tex')

Depends(pdf, form_tex) # this dependency is not working. The result of form_tex is kept in the repo to avoid this problem
Depends(form_tex, cp_imgs)
Depends(pdf, cp_imgs)

cleans = scan_files('.', accept=["proton_fiducial*", "*.aux"], reject=[".tex"])
Clean('electron_fiducial.html', cleans)
