name: Pubs pdf build

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize
`
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build the geometry and plugins, runs jcard in tests directory
  build_pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: maureeungaro/base:fedora36-latex
    name: PDF ${{ matrix.doc }}
    strategy:
      fail-fast: false
      matrix:
        doc:
          - pi0_resonance_regions/pid/electron
          - pi0_resonance_regions/pid/proton
          - pi0_resonance_regions/vertex
          - pi0_resonance_regions/fiducial/electron
          - pi0_resonance_regions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: ${{ matrix.doc }}
        run: |
          ./ci/make_pdf.sh -d ${{ matrix.doc }}

      # https://github.com/stefanzweifel/git-auto-commit-action
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
          file_pattern: 'pdfs/*.pdf'
      - uses: gitboard-io/gitboard-action@main
        with:
          username: maureeungaro
          key: 3d8e9059-a164-4bea-9541-1cb8789d805b